# Generated by Django 4.0.5 on 2022-06-26 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_pic',
        ),
    ]
